# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/principles-of-automatic-controls',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/principles-of-automatic-controls',
                'lib_path': 'principles_of_automatic_controls'},
  'syms': { 'principles_of_automatic_controls.introduction_to_control_problem': { 'principles_of_automatic_controls.introduction_to_control_problem.draw_mass_spring_damper': ( 'introduction_to_control_problem.html#draw_mass_spring_damper',
                                                                                                                                                                                'principles_of_automatic_controls/introduction_to_control_problem.py')}}}
