# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/principles-of-automatic-controls',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/principles-of-automatic-controls',
                'lib_path': 'principles_of_automatic_controls'},
  'syms': { 'principles_of_automatic_controls.core': { 'principles_of_automatic_controls.core.foo': ( 'core.html#foo',
                                                                                                      'principles_of_automatic_controls/core.py')}}}
